- name: check if anaconda is installed
  stat: path={{ anaconda_path }}
  register: anaconda_dir

- name: download miniconda
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    dest: /tmp
    force: no
  when: anaconda_dir.stat.exists == False

- name: install miniconda
  shell: bash /tmp/Miniconda-latest-Linux-x86_64.sh -b -p {{ anaconda_path }}
  args:
    creates: "{{ anaconda_path }}"
  when: anaconda_dir.stat.exists == False

- name: update conda
  shell: "{{ conda }} update -y conda"
  when: anaconda_dir.stat.exists == False

- name: check if conda environment exists
  stat: path="{{ anaconda_path }}/envs/{{ r3vol_env }}"
  register: r3vol_env_dir

- name: create r3vol conda env
  shell: "{{ conda }} create -y -n {{ r3vol_env }} python"
  when: r3vol_env_dir.stat.exists == False

- name: copy requirements
  template: src={{ inventory_dir }}/requirements.yaml dest=/tmp/requirements.yaml

- name: install required r3vol packages
  shell: "{{ conda }} env update -n {{ r3vol_env }} --file /tmp/requirements.yaml"