- name: playbook to install R3vol
  hosts: all
  serial: 1
  vars:
    local_path: /home/{{ ansible_ssh_user }}
    anaconda_path: "{{ local_path }}/{{ anacondadir }}"
    default_r3vol_path: "{{ r3vol_location }}/r3vol"
    conda: "{{ anaconda_path }}/bin/conda"
    env_path: "{{ anaconda_path }}/envs/{{ r3vol_env }}/bin"
    python: "{{ anaconda_path }}/envs/{{ r3vol_env }}/bin/python"
  tasks:

    - include: r3vol_path.yaml
      tags: [always]

    - include: clone.yaml
      tags: [install]

    - include: mongo.yaml
      tags: [install]
      when: inventory_hostname in groups['db']


    - include: conda.yaml
      tags: [install]
      when: >
        inventory_hostname in groups['db'] or
        inventory_hostname in groups['api'] or
        inventory_hostname in groups['cloud']

    - include: view.yaml
      tags: [install]
      when: >
        ansible_ssh_host == 'localhost' and
        inventory_hostname in groups['frontend']

    - name: install nginx, python-httplib2
      tags: [install]
      apt:
        name: "{{ item }}"
        state: present
        force: yes
      become: true
      with_items:
        - nginx
        - python-httplib2
      when: >
        inventory_hostname in groups['frontend'] or
        inventory_hostname in groups['api'] or
        inventory_hostname in groups['cloud']

    - include: serve_frontend.yaml
      when: inventory_hostname in groups['frontend']
      tags: [serve]
