- name: install git
  apt:
    name: git
    state: present
    force: yes
  become: true

- name: Get playbook path
  shell: cd {{ r3vol_location }}; git rev-parse --show-toplevel
  register: rev_parse
  ignore_errors: true

- name: set r3vol_path local
  set_fact:
    r3vol_path: "{{ rev_parse.stdout }}"
  when: rev_parse.rc == 0

- name: set r3vol_path default
  set_fact:
    r3vol_path: "{{ default_r3vol_path }}"
  when: rev_parse.rc != 0

- name: echo rev_parse
  shell: echo {{ rev_parse }}